### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by chenyutao36** [adbuerger/pycombina#9]
Hello there,

I want use pycombina for my work (I used CPLEX before). However, I encounter installation errors on two different PCs, one with Intel CPU and the other with AMD.

The error messages for the two PCs are the same, and I put the screenshot here for you. 

I installed MSVS 2019 community and Anaconda 2020.11, both in x64 version. I also installed CMake in Anaconda and in Windows. Could you help me solve this problem?

Best regards,

Yutao 

![QQ图片20210309181546](https://user-images.githubusercontent.com/10599537/110455743-c2eb0800-8103-11eb-8e4a-1baceccf1740.png)

**Comment by mirhahn** [comment]
This seems to be nothing more than an error with includes. `back_inserter` comes from `<iterator>`. Can't find `clock_t`, which is probably a pycombina-internal Chrono-typedef. I can figure that out later today and make a pull request. The problem is most likely that these are cross-included by other STL headers on the systems that we test on.

*Edit:* `clock_t` appears to be a standard C type located in `<ctime>`.

**Comment by adbuerger** [comment]
I included the fixes by @mirhahn in the master branch. @chenyutao36 could you please try again to install and let us know if these changes fix the problem?

**Comment by chenyutao36** [comment]
Thank you @mirhahn  and @adbuerger. The problem is fixed.

**Comment by adbuerger** [comment]
Great to hear! Thanks for letting us know and for reporting the problem.
